{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.hakkabara.cli;
in
{
  options.hakkabara.cli = {
    enable = lib.mkEnableOption "shared command-line tool environment";

    yazi.extraKeymap = lib.mkOption {
      type = lib.types.listOf (lib.types.attrsOf lib.types.anything);
      default = [ ];
      description = "Additional Yazi manager keybindings supplied by profiles or hosts.";
    };
  };

  config = lib.mkIf cfg.enable {
    programs = {
      # Better cat-like viewer.
      # Keep the real `cat` command unchanged.
      bat.enable = true;

      # Modern interactive replacement for ls.
      eza = {
        enable = true;
        enableZshIntegration = true;

        icons = "auto";
        colors = "auto";
        git = true;

        extraOptions = [
          "--group-directories-first"
        ];
      };

      # Terminal file manager.
      yazi = {
        enable = true;
        enableZshIntegration = true;

        # Shared Yazi bindings live here.
        #
        # Profiles and individual hosts can append bindings through:
        #
        #   hakkabara.cli.yazi.extraKeymap
        #
        # This keeps universal behavior separate from machine-specific paths.
        keymap.mgr.prepend_keymap = [
          {
            on = [
              "g"
              "l"
            ];

            # lnav is an interactive TUI.  --block temporarily gives the
            # terminal to lnav and lets Yazi resume cleanly when lnav exits.
            #
            # lib.getExe resolves the exact lnav executable from our Nixpkgs
            # package instead of depending on an arbitrary PATH lookup.
            run = "shell --block -- ${lib.getExe pkgs.lnav} %h";
            desc = "Open hovered file in lnav";
          }
        ]
        ++ cfg.yazi.extraKeymap;
      };

      # System monitor.
      btop = {
        enable = true;

        settings = {
          # Dynamic colors generated by Matugen.
          color_theme = "matugen";
          theme_background = false;
          truecolor = true;

          # UI / controls.
          rounded_corners = true;
          terminal_sync = true;
          graph_symbol = "braille";
          vim_keys = true;

          # Slightly more responsive than upstream's 2000 ms default.
          update_ms = 1500;

          # Main layout.
          shown_boxes = "cpu mem net proc";

          # Processes.
          proc_sorting = "cpu direct";
          proc_tree = false;
          proc_colors = true;
          proc_gradient = true;
          proc_mem_bytes = true;
          proc_cpu_graphs = true;
          proc_filter_kernel = true;
          proc_follow_detailed = true;
          proc_tree_auto_collapse = 5;

          # CPU.
          cpu_graph_upper = "total";
          cpu_graph_lower = "Auto";
          cpu_invert_lower = true;
          cpu_single_graph = false;

          show_uptime = true;
          check_temp = true;
          show_coretemp = true;
          show_cpu_freq = true;
          freq_mode = "average";

          # Memory / disks.
          mem_graphs = true;
          show_swap = true;
          show_disks = true;
          show_io_stat = true;

          # Network.
          net_auto = true;
          net_sync = true;
          base_10_bitrate = true;

          # Useful when multiple VMs are open.
          clock_format = "%H:%M  /host  /uptime";

          log_level = "WARNING";
        };
      };

      # Git TUI.
      lazygit = {
        enable = true;
        enableZshIntegration = true;
      };

      # Better Git diff rendering.
      delta = {
        enable = true;
        enableGitIntegration = true;

        options = {
          navigate = true;
          line-numbers = true;
        };
      };
    };

    home.packages = with pkgs; [
      # Search
      ripgrep
      fd

      # Structured data
      jq
      yq-go
      # Files / navigation
      tree
      file
      less

      # Disk usage
      duf
      dust

      # Processes / logs
      procs

      # HTTP / networking
      curl
      wget
      xh
      miniserve
      speedtest-go

      # File transfer / sync
      rsync

      # Archives
      zip
      unzip
      _7zz
      ouch

      # Documentation / benchmarking
      tealdeer
      hyperfine
    ];
  };
}
