# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "mptspi"
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4531eb50-9011-4952-aa7b-e60dafd31409";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c5b6bd93-411a-45ca-8ab1-7a742e753f0d"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
