# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "mptspi"
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/60a9d808-9611-417d-8792-68410a23d6d6";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/83389e1b-a240-45d5-bce2-336963c906e7"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
