{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.hakkabara.desktop.niri;

  dmsBinds = lib.optionalString cfg.dmsIntegration.enable ''
    // DankMaterialShell IPC integration.
    //
    // Keep Niri's standard window-management bindings available and put
    // WorkVM-specific shell functions on otherwise unused combinations.

    Mod+D hotkey-overlay-title="Application Launcher" {
        spawn "dms" "ipc" "call" "spotlight" "toggle";
    }

    Mod+N hotkey-overlay-title="Notifications" {
        spawn "dms" "ipc" "call" "notifications" "toggle";
    }

    Mod+Ctrl+Comma hotkey-overlay-title="DMS Settings" {
        spawn "dms" "ipc" "call" "settings" "toggle";
    }

    Mod+P hotkey-overlay-title="Notepad" {
        spawn "dms" "ipc" "call" "notepad" "toggle";
    }

    Mod+Ctrl+V hotkey-overlay-title="CopyQ Clipboard" {
        spawn "copyq" "-e" "toggle()";
    }

    Mod+X hotkey-overlay-title="Power Menu" {
        spawn "dms" "ipc" "call" "powermenu" "toggle";
    }

    // Super+L is intercepted by the Windows/VMware host.
    Super+Alt+L hotkey-overlay-title="Lock Session" {
        spawn "dms" "ipc" "call" "lock" "lock";
    }
  '';
in
{
  options.hakkabara.desktop.niri = {
    enable = lib.mkEnableOption "declarative Niri configuration managed through Home Manager";

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "kitty";
      description = "Terminal command launched from Niri.";
    };

    gaps = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 16;
      description = "Niri layout gap in logical pixels.";
    };

    dmsIntegration.enable = lib.mkEnableOption "DankMaterialShell IPC key bindings";

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = ''
        Additional Niri KDL appended to the reusable baseline.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Keep the cursor consistent across Niri, GTK, XWayland and
    # applications launched through DMS/systemd.
    home.pointerCursor = {
      enable = true;
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Ice";
      size = 20;

      gtk.enable = true;
      x11.enable = true;
    };

    # Home Manager 26.05 does not yet contain the newer typed Niri module.
    # Managing config.kdl with xdg.configFile remains fully declarative and
    # keeps the configuration in the Nix repository.
    xdg.configFile."niri/config.kdl".text = ''
      // Generated by Home Manager.
      // Do not edit ~/.config/niri/config.kdl manually.

      prefer-no-csd

      // Compact desktop cursor.
      cursor {
          xcursor-theme "Bibata-Modern-Ice"
          xcursor-size 20
      }

      hotkey-overlay {
          skip-at-startup
      }

      // NIRI RICE: Tokyo Night
      layout {
          gaps ${toString cfg.gaps}

          // Keep single windows centered while retaining Niri's
          // scrolling-column behavior once the workspace gets busy.
          center-focused-column "on-overflow"
          always-center-single-column

          background-color "#1a1b26"

          preset-column-widths {
              proportion 0.33333
              proportion 0.5
              proportion 0.66667
          }

          default-column-width {
              proportion 0.5
          }

          // Thin Tokyo Night border instead of the default focus ring.
          focus-ring {
              off
          }

          border {
              on
              width 2
              active-color "#7aa2f7"
              inactive-color "#3b4261"
              urgent-color "#f7768e"
          }

          // Subtle depth around windows.
          shadow {
              on
              softness 24
              spread -2
              offset x=0 y=4
              color "#00000066"
              inactive-color "#00000040"
          }

          // Placement hint when moving windows/columns.
          insert-hint {
              on
              color "#bb9af780"
          }

          // Mostly invisible until tabbed columns are used.
          tab-indicator {
              on
              hide-when-single-tab
              place-within-column
              gap 5
              width 4
              length total-proportion=1.0
              position "top"
              gaps-between-tabs 4
              corner-radius 8

              active-color "#7aa2f7"
              inactive-color "#3b4261"
              urgent-color "#f7768e"
          }
      }

      // Crisp rather than floaty animations.
      animations {
          workspace-switch {
              spring damping-ratio=1.0 stiffness=900 epsilon=0.0001
          }

          horizontal-view-movement {
              spring damping-ratio=1.0 stiffness=850 epsilon=0.0001
          }

          window-movement {
              spring damping-ratio=1.0 stiffness=850 epsilon=0.0001
          }

          window-resize {
              spring damping-ratio=1.0 stiffness=900 epsilon=0.0001
          }

          window-open {
              duration-ms 140
              curve "ease-out-quad"
          }

          window-close {
              duration-ms 120
              curve "ease-out-cubic"
          }

          overview-open-close {
              spring damping-ratio=1.0 stiffness=850 epsilon=0.0001
          }
      }

      // Uniform rounded corners for normal and floating applications.
      window-rule {
          geometry-corner-radius 12
          clip-to-geometry true
      }


      // CopyQ acts as a transient clipboard overlay.
      // Match the KDE Plasma clipboard popup proportions while Niri
      // keeps the floating window centered.
      window-rule {
          match app-id=r#"^com\.github\.hluk\.copyq$"#

          open-floating true
          open-maximized false
          default-floating-position x=0 y=0 relative-to="bottom"

          // Plasma reference: 647x629 on a 2558x1280 output.
          default-column-width { proportion 0.253; }
          default-window-height { proportion 0.491; }
      }

      binds {
          // Important-hotkey overview.
          Mod+Shift+Slash { show-hotkey-overlay; }

          // Applications.
          Mod+Return hotkey-overlay-title="Terminal" {
              spawn "${cfg.terminal}";
          }
          Mod+T hotkey-overlay-title="Terminal" {
              spawn "${cfg.terminal}";
          }

          // Frequently used applications.
          Mod+B hotkey-overlay-title="Browser" {
              spawn "floorp-xwayland-glx" "--name" "floorp";
          }

          Mod+E hotkey-overlay-title="File Manager (Yazi)" {
              spawn "kitty" "-e" "yazi";
          }

          // Overview and basic window lifecycle.
          // Familiar Windows/TailorKey Task View behavior.
          Mod+Tab repeat=false hotkey-overlay-title="Task View / Overview" {
            toggle-overview;
          }

          Mod+O repeat=false { toggle-overview; }
          Mod+Q repeat=false { close-window; }

          // Focus: arrows and Vim-style H/J/K/L.
          Mod+Left  { focus-column-left; }
          Mod+Down  { focus-window-down; }
          Mod+Up    { focus-window-up; }
          Mod+Right { focus-column-right; }

          Mod+H { focus-column-left; }
          Mod+J { focus-window-down; }
          Mod+K { focus-window-up; }
          Mod+L { focus-column-right; }

          // Move windows/columns.
          Mod+Ctrl+Left  { move-column-left; }
          Mod+Ctrl+Down  { move-window-down; }
          Mod+Ctrl+Up    { move-window-up; }
          Mod+Ctrl+Right { move-column-right; }

          Mod+Ctrl+H { move-column-left; }
          Mod+Ctrl+J { move-window-down; }
          Mod+Ctrl+K { move-window-up; }
          Mod+Ctrl+L { move-column-right; }

          // First/last column.
          Mod+Home { focus-column-first; }
          Mod+End { focus-column-last; }
          Mod+Ctrl+Home { move-column-to-first; }
          Mod+Ctrl+End { move-column-to-last; }

          // Monitor navigation.
          Mod+Shift+Left  { focus-monitor-left; }
          Mod+Shift+Down  { focus-monitor-down; }
          Mod+Shift+Up    { focus-monitor-up; }
          Mod+Shift+Right { focus-monitor-right; }

          Mod+Shift+H { focus-monitor-left; }
          Mod+Shift+J { focus-monitor-down; }
          Mod+Shift+K { focus-monitor-up; }
          Mod+Shift+L { focus-monitor-right; }

          // Move a complete column between monitors.
          Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
          Mod+Shift+Ctrl+Down  { move-column-to-monitor-down; }
          Mod+Shift+Ctrl+Up    { move-column-to-monitor-up; }
          Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }

          Mod+Shift+Ctrl+H { move-column-to-monitor-left; }
          Mod+Shift+Ctrl+J { move-column-to-monitor-down; }
          Mod+Shift+Ctrl+K { move-column-to-monitor-up; }
          Mod+Shift+Ctrl+L { move-column-to-monitor-right; }

          // Dynamic workspaces.
          Mod+Page_Down { focus-workspace-down; }
          Mod+Page_Up { focus-workspace-up; }
          Mod+U { focus-workspace-down; }
          Mod+I { focus-workspace-up; }

          Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
          Mod+Ctrl+Page_Up { move-column-to-workspace-up; }
          Mod+Ctrl+U { move-column-to-workspace-down; }
          Mod+Ctrl+I { move-column-to-workspace-up; }

          Mod+Shift+Page_Down { move-workspace-down; }
          Mod+Shift+Page_Up { move-workspace-up; }
          Mod+Shift+U { move-workspace-down; }
          Mod+Shift+I { move-workspace-up; }

          // Workspace switching with mouse wheel.
          Mod+WheelScrollDown cooldown-ms=150 { focus-workspace-down; }
          Mod+WheelScrollUp cooldown-ms=150 { focus-workspace-up; }
          Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
          Mod+Ctrl+WheelScrollUp cooldown-ms=150 { move-column-to-workspace-up; }

          Mod+WheelScrollRight { focus-column-right; }
          Mod+WheelScrollLeft { focus-column-left; }
          Mod+Ctrl+WheelScrollRight { move-column-right; }
          Mod+Ctrl+WheelScrollLeft { move-column-left; }

          Mod+Shift+WheelScrollDown { focus-column-right; }
          Mod+Shift+WheelScrollUp { focus-column-left; }
          Mod+Ctrl+Shift+WheelScrollDown { move-column-right; }
          Mod+Ctrl+Shift+WheelScrollUp { move-column-left; }

          // Explicit workspace numbers.
          Mod+1 { focus-workspace 1; }
          Mod+2 { focus-workspace 2; }
          Mod+3 { focus-workspace 3; }
          Mod+4 { focus-workspace 4; }
          Mod+5 { focus-workspace 5; }
          Mod+6 { focus-workspace 6; }
          Mod+7 { focus-workspace 7; }
          Mod+8 { focus-workspace 8; }
          Mod+9 { focus-workspace 9; }

          // Move only the focused window to a numbered workspace.
          // This mirrors the familiar i3/Sway Super+Shift+number workflow.
          Mod+Shift+1 { move-window-to-workspace 1; }
          Mod+Shift+2 { move-window-to-workspace 2; }
          Mod+Shift+3 { move-window-to-workspace 3; }
          Mod+Shift+4 { move-window-to-workspace 4; }
          Mod+Shift+5 { move-window-to-workspace 5; }
          Mod+Shift+6 { move-window-to-workspace 6; }
          Mod+Shift+7 { move-window-to-workspace 7; }
          Mod+Shift+8 { move-window-to-workspace 8; }
          Mod+Shift+9 { move-window-to-workspace 9; }

          // Move the complete Niri column to a numbered workspace.
          Mod+Ctrl+1 { move-column-to-workspace 1; }
          Mod+Ctrl+2 { move-column-to-workspace 2; }
          Mod+Ctrl+3 { move-column-to-workspace 3; }
          Mod+Ctrl+4 { move-column-to-workspace 4; }
          Mod+Ctrl+5 { move-column-to-workspace 5; }
          Mod+Ctrl+6 { move-column-to-workspace 6; }
          Mod+Ctrl+7 { move-column-to-workspace 7; }
          Mod+Ctrl+8 { move-column-to-workspace 8; }
          Mod+Ctrl+9 { move-column-to-workspace 9; }

          // Column composition.
          Mod+BracketLeft { consume-or-expel-window-left; }
          Mod+BracketRight { consume-or-expel-window-right; }
          Mod+Comma { consume-window-into-column; }
          Mod+Period { expel-window-from-column; }

          // Column/window sizing.
          Mod+R { switch-preset-column-width; }
          Mod+Shift+R { switch-preset-column-width-back; }
          Mod+Ctrl+Shift+R { switch-preset-window-height; }
          Mod+Ctrl+R { reset-window-height; }

          Mod+F { maximize-column; }
          Mod+Shift+F { fullscreen-window; }
          Mod+M { maximize-window-to-edges; }
          Mod+Ctrl+F { expand-column-to-available-width; }

          Mod+C { center-column; }
          Mod+Ctrl+C { center-visible-columns; }

          // Consistent arrow-key workflow:
          // Super        = focus
          // Super+Ctrl   = move
          // Super+Alt    = resize
          // Super+Shift  = monitor
          Mod+Alt+Left  { set-column-width "-10%"; }
          Mod+Alt+Right { set-column-width "+10%"; }
          Mod+Alt+Up    { set-window-height "-10%"; }
          Mod+Alt+Down  { set-window-height "+10%"; }

          // EurKEY/AltGr path used by the Glove80 TailorKey thumb key.
          Mod+Mod5+Left  { set-column-width "-10%"; }
          Mod+Mod5+Right { set-column-width "+10%"; }
          Mod+Mod5+Up    { set-window-height "-10%"; }
          Mod+Mod5+Down  { set-window-height "+10%"; }

          // TailorKey directional resize on the home-row-like J/K/L/; cluster.
          // J = left, K = up, L = down, ; = right.
          Mod+Mod5+J hotkey-overlay-title="Resize — TailorKey J/K/L/;" {
            set-column-width "-10%";
          }
          Mod+Mod5+K { set-window-height "-10%"; }
          Mod+Mod5+L { set-window-height "+10%"; }
          Mod+Mod5+Semicolon { set-column-width "+10%"; }

          Mod+Minus { set-column-width "-10%"; }
          Mod+Equal { set-column-width "+10%"; }
          Mod+Shift+Minus { set-window-height "-10%"; }
          Mod+Shift+Equal { set-window-height "+10%"; }

          // Floating and tabbed columns.
          Mod+V { toggle-window-floating; }
          Mod+Shift+V { switch-focus-between-floating-and-tiling; }
          Mod+W { toggle-column-tabbed-display; }

          // Use Flameshot consistently across desktop environments.
          // Niri's native screenshot actions remain intentionally unbound.
          Mod+Shift+S hotkey-overlay-title="Flameshot Screenshot" {
              spawn "flameshot" "gui";
          }

          // Escape hatch for RDP/VM applications requesting shortcut inhibition.
          Mod+Escape allow-inhibiting=false {
              toggle-keyboard-shortcuts-inhibit;
          }

          Mod+Shift+E { quit; }

          ${dmsBinds}
      }

      ${cfg.extraConfig}
    '';
  };
}
