{
  config,
  lib,
  ...
}:

let
  cfg = config.hakkabara.desktop.niri;

  dmsBinds = lib.optionalString cfg.dmsIntegration.enable ''
    // DankMaterialShell IPC integration.
    //
    // DMS itself is started through its Home Manager systemd service.
    // These bindings only invoke DMS functionality.

    Mod+Space hotkey-overlay-title="Application Launcher" {
        spawn "dms" "ipc" "call" "spotlight" "toggle";
    }

    Mod+N hotkey-overlay-title="Notifications" {
        spawn "dms" "ipc" "call" "notifications" "toggle";
    }

    Mod+Comma hotkey-overlay-title="DMS Settings" {
        spawn "dms" "ipc" "call" "settings" "toggle";
    }

    Mod+P hotkey-overlay-title="Notepad" {
        spawn "dms" "ipc" "call" "notepad" "toggle";
    }

    Mod+V hotkey-overlay-title="CopyQ Clipboard" {
        spawn "copyq" "-e" "toggle()";
    }

    Mod+X hotkey-overlay-title="Power Menu" {
        spawn "dms" "ipc" "call" "powermenu" "toggle";
    }

    Super+Alt+L hotkey-overlay-title="Lock Session" {
        spawn "dms" "ipc" "call" "lock" "lock";
    }
  '';
in
{
  options.hakkabara.desktop.niri = {
    enable = lib.mkEnableOption "declarative Niri configuration managed through Home Manager";

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "kitty";
      description = "Terminal command launched from Niri.";
    };

    gaps = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 8;
      description = "Niri layout gap in logical pixels.";
    };

    dmsIntegration.enable = lib.mkEnableOption "DankMaterialShell IPC key bindings";

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = ''
        Additional Niri KDL appended to the reusable baseline.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Home Manager 26.05 does not yet contain the newer typed Niri module.
    # Managing config.kdl with xdg.configFile remains fully declarative and
    # keeps the configuration in the Nix repository.
    xdg.configFile."niri/config.kdl".text = ''
      // Generated by Home Manager.
      // Do not edit ~/.config/niri/config.kdl manually.

      prefer-no-csd

      hotkey-overlay {
          skip-at-startup
      }

      layout {
          gaps ${toString cfg.gaps}

          preset-column-widths {
              proportion 0.33333
              proportion 0.5
              proportion 0.66667
          }

          default-column-width {
              proportion 0.5
          }
      }


      // CopyQ acts as a transient clipboard overlay.
      // Match the KDE Plasma clipboard popup proportions while Niri
      // keeps the floating window centered.
      window-rule {
          match app-id=r#"^com\.github\.hluk\.copyq$"#

          open-floating true
          open-maximized false
          default-floating-position x=0 y=0 relative-to="bottom"

          // Plasma reference: 647x629 on a 2558x1280 output.
          default-column-width { proportion 0.253; }
          default-window-height { proportion 0.491; }
      }

      binds {
          Mod+Return hotkey-overlay-title="Terminal" {
              spawn "${cfg.terminal}";
          }

          Mod+H { focus-column-left; }
          Mod+J { focus-window-down; }
          Mod+K { focus-window-up; }
          Mod+L { focus-column-right; }

          Mod+Ctrl+H { move-column-left; }
          Mod+Ctrl+J { move-window-down; }
          Mod+Ctrl+K { move-window-up; }
          Mod+Ctrl+L { move-column-right; }

          Mod+1 { focus-workspace 1; }
          Mod+2 { focus-workspace 2; }
          Mod+3 { focus-workspace 3; }
          Mod+4 { focus-workspace 4; }
          Mod+5 { focus-workspace 5; }
          Mod+6 { focus-workspace 6; }
          Mod+7 { focus-workspace 7; }
          Mod+8 { focus-workspace 8; }
          Mod+9 { focus-workspace 9; }

          Mod+Shift+1 { move-column-to-workspace 1; }
          Mod+Shift+2 { move-column-to-workspace 2; }
          Mod+Shift+3 { move-column-to-workspace 3; }
          Mod+Shift+4 { move-column-to-workspace 4; }
          Mod+Shift+5 { move-column-to-workspace 5; }
          Mod+Shift+6 { move-column-to-workspace 6; }
          Mod+Shift+7 { move-column-to-workspace 7; }
          Mod+Shift+8 { move-column-to-workspace 8; }
          Mod+Shift+9 { move-column-to-workspace 9; }

          Mod+F { fullscreen-window; }

          Mod+Shift+Q { close-window; }

          Print { screenshot; }
          Ctrl+Print { screenshot-screen; }
          Alt+Print { screenshot-window; }

          // Useful for RDP/VM applications that request shortcut inhibition.
          Mod+Escape allow-inhibiting=false {
              toggle-keyboard-shortcuts-inhibit;
          }

          Mod+Shift+E { quit; }

          ${dmsBinds}
      }

      ${cfg.extraConfig}
    '';
  };
}
