{
  config,
  lib,
  pkgs,
  pkgsUnstable,
  ...
}:

let
  cfg = config.hakkabara.terminal;
in
{
  config = lib.mkIf (cfg.enable && cfg.zellij.enable) {
    # xclip is used by Zellij to write directly to the X11 system clipboard.
    home.packages = [
      pkgs.xclip
      # Lightweight CPU/RAM source for zjstatus.
      #
      # Linux already exposes the required counters through /proc, so we do
      # not need another monitoring daemon just for the status bar.
      (pkgs.writeShellApplication {
        name = "zjstatus-system";

        # `sleep` is used for the short CPU utilization sample.
        runtimeInputs = [
          pkgs.coreutils
        ];

        text = ''
          read_cpu() {
            local -a fields
            local idle_all
            local total
            local i

            read -r -a fields < /proc/stat

            # /proc/stat:
            # cpu user nice system idle iowait irq softirq steal ...
            idle_all=$((fields[4] + fields[5]))

            total=0
            for i in {1..8}; do
              total=$((total + fields[i]))
            done

            printf '%s %s\n' "$total" "$idle_all"
          }

          # CPU utilization is a delta, not an instantaneous counter.
          # Take two short local samples so every invocation is independent
          # and multiple Zellij sessions cannot race over a shared state file.
          read -r total_before idle_before < <(read_cpu)
          sleep 0.1
          read -r total_after idle_after < <(read_cpu)

          total_delta=$((total_after - total_before))
          idle_delta=$((idle_after - idle_before))

          cpu_pct=0

          if (( total_delta > 0 )); then
            cpu_pct=$((100 * (total_delta - idle_delta) / total_delta))
          fi

          # RAM values from /proc/meminfo are expressed in KiB.
          mem_total=0
          mem_available=0

          while read -r key value _; do
            case "$key" in
              MemTotal:)
                mem_total="$value"
                ;;
              MemAvailable:)
                mem_available="$value"
                ;;
            esac
          done < /proc/meminfo

          if (( mem_total <= 0 )); then
            echo "ERROR: MemTotal missing from /proc/meminfo" >&2
            exit 1
          fi

          mem_used=$((mem_total - mem_available))
          mem_pct=$((100 * mem_used / mem_total))

          # Render one decimal place without pulling in awk/bc.
          used_tenths=$((mem_used * 10 / 1048576))
          total_tenths=$((mem_total * 10 / 1048576))

          used_gib="$((used_tenths / 10)).$((used_tenths % 10))G"
          total_gib="$((total_tenths / 10)).$((total_tenths % 10))G"

          # command_system_rendermode=dynamic makes zjstatus interpret these
          # formatting directives from stdout.
          printf \
            '#[bg=#7aa2f7,fg=#1a1b26,bold]  CPU %s%% #[bg=#bb9af7,fg=#1a1b26,bold] 󰍛 RAM %s%% %s/%s #[bg=#1a1b26]\n' \
            "$cpu_pct" \
            "$mem_pct" \
            "$used_gib" \
            "$total_gib"
        '';
      })
    ];

    # Zellij identifies third-party plugins by their path. Pointing Zellij
    # directly at /nix/store paths would make the identity change after every
    # package update, which can cause permission prompts to reappear.
    #
    # Home Manager therefore exposes stable paths below ~/.config/zellij while
    # the symlink targets remain immutable Nix store objects.
    xdg.configFile = {
      "zellij/plugins/zellij-autolock.wasm".source =
        pkgsUnstable.zellijPlugins.autolock;

      "zellij/plugins/vim-zellij-navigator.wasm".source =
        pkgsUnstable.zellijPlugins.vim-zellij-navigator;

      "zellij/plugins/zjstatus.wasm".source =
        pkgsUnstable.zellijPlugins.zjstatus;

      # Declarative KDL layouts. Keep the repository versions as the source
      # of truth; ~/.config/zellij/layouts is generated by Home Manager.
      "zellij/layouts/default.kdl".source =
        ./zellij/layouts/default.kdl;

    };

    programs.zellij = {
      enable = true;

      # Zellij moves faster than the NixOS stable package set.
      #
      # Only Zellij opts into nixos-unstable; the rest of the terminal
      # environment continues to use the stable `pkgs` package set.
      package = pkgsUnstable.zellij;

      # Zellij should be started explicitly, not automatically for every Zsh.
      enableZshIntegration = false;

      # KDL that is easier to express verbatim than through the generic
      # Home Manager settings-to-KDL converter.
      #
      # Autolock is defined here but intentionally NOT loaded automatically
      # yet. We first grant its permissions interactively in a later step.
      extraConfig = ''
        plugins {
          autolock location="file:${config.xdg.configHome}/zellij/plugins/zellij-autolock.wasm" {
            is_enabled true
            triggers "nvim|vim|fzf"
            reaction_seconds "0.3"
            print_to_log false
          }

          vim_zellij_navigator location="file:${config.xdg.configHome}/zellij/plugins/vim-zellij-navigator.wasm"

          // Installed now; activated as the status bar in the next UI step.
          zjstatus location="file:${config.xdg.configHome}/zellij/plugins/zjstatus.wasm"
        }

        // Autolock is a headless plugin and needs to stay alive for the
        // whole Zellij session. Permissions were granted once interactively and
        // are persisted by Zellij in its permission cache.
        load_plugins {
          autolock
        }

        keybinds {
          // Autolock reacts to PaneUpdate/InputReceived events. Intercepting
          // Enter in Normal mode lets it immediately reassess the command that
          // has just been started instead of waiting for the reaction timer.
          normal {
            bind "Enter" {
              WriteChars "\u{000D}";
              MessagePlugin "autolock" {};
            }
          }

          // Emergency escape while an application caused Zellij to lock.
          // This disables autolock and returns control to Zellij Normal mode.
          locked {
            bind "Alt z" {
              MessagePlugin "autolock" {payload "disable";};
              SwitchToMode "Normal";
            }
          }

          // Explicitly re-enable autolock after using the emergency escape.
          shared {
            bind "Alt Shift z" {
              MessagePlugin "autolock" {payload "enable";};
            }
          }

          // These mappings are active while Zellij itself owns the keyboard.
          // When Autolock later puts a Neovim pane into Locked mode, the same
          // keys pass directly to Neovim/smart-splits instead.
          shared_except "locked" {
            bind "Ctrl h" {
              MessagePlugin "vim_zellij_navigator" {
                name "move_focus";
                payload "left";
                move_mod "ctrl";
                use_arrow_keys "false";
              };
            }

            bind "Ctrl j" {
              MessagePlugin "vim_zellij_navigator" {
                name "move_focus";
                payload "down";
                move_mod "ctrl";
                use_arrow_keys "false";
              };
            }

            bind "Ctrl k" {
              MessagePlugin "vim_zellij_navigator" {
                name "move_focus";
                payload "up";
                move_mod "ctrl";
                use_arrow_keys "false";
              };
            }

            bind "Ctrl l" {
              MessagePlugin "vim_zellij_navigator" {
                name "move_focus";
                payload "right";
                move_mod "ctrl";
                use_arrow_keys "false";
              };
            }

            bind "Alt h" {
              MessagePlugin "vim_zellij_navigator" {
                name "resize";
                payload "left";
                resize_mod "alt";
              };
            }

            bind "Alt j" {
              MessagePlugin "vim_zellij_navigator" {
                name "resize";
                payload "down";
                resize_mod "alt";
              };
            }

            bind "Alt k" {
              MessagePlugin "vim_zellij_navigator" {
                name "resize";
                payload "up";
                resize_mod "alt";
              };
            }

            bind "Alt l" {
              MessagePlugin "vim_zellij_navigator" {
                name "resize";
                payload "right";
                resize_mod "alt";
              };
            }
          }
        }
      '';

      settings = {
        # -----------------------------------------------------------------------
        # Appearance
        # -----------------------------------------------------------------------

        theme = "tokyo-night";
        default_layout = "default";

        # Keep pane borders for orientation.
        pane_frames = true;

        # -----------------------------------------------------------------------
        # Mouse / history
        # -----------------------------------------------------------------------

        mouse_mode = true;
        scroll_buffer_size = 250000;

        # -----------------------------------------------------------------------
        # Clipboard
        # -----------------------------------------------------------------------

        # Zellij pipes the selected text to xclip.
        # This bypasses the OSC52 issue we observed with Kitty/X11.
        copy_command = "xclip -selection clipboard";

        # Copy as soon as the mouse selection is released.
        copy_on_select = true;

        # -----------------------------------------------------------------------
        # Sessions
        # -----------------------------------------------------------------------

        on_force_close = "detach";

        # Save enough metadata to resurrect the session structure.
        session_serialization = true;

        # Do NOT persist visible terminal contents to disk.
        pane_viewport_serialization = false;

        serialization_interval = 60;

        show_startup_tips = true;
        show_release_notes = false;

        # -----------------------------------------------------------------------
        # Terminal capabilities
        # -----------------------------------------------------------------------

        osc8_hyperlinks = true;
        support_kitty_keyboard_protocol = true;

        visual_bell = false;

        # -----------------------------------------------------------------------
        # Web functionality
        # -----------------------------------------------------------------------

        web_server = false;
      };
    };
  };
}
